# Generated by Django 3.1.5 on 2021-01-24 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_profile_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='nachname',
            field=models.CharField(max_length=150),
        ),
    ]
